import Footer from "@/components/molecules/Footers/Footer/Footer";
import ReduxProvider from "@/redux/ReduxProvider";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ReduxProvider>
      <html lang="en">
        <head></head>
        <body id="main-layout">
          {children} <Footer />
        </body>
      </html>
    </ReduxProvider>
  );
}
