import NextAuthProvider from "@/components/atoms/Providers/SessionProvider/SessionProvider";
import Footer from "@/components/molecules/Footers/Footer/Footer";
import ReduxProvider from "@/redux/ReduxProvider";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/nextAuth";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession(authOptions);
  return (
    <NextAuthProvider session={session}>
      <ReduxProvider>
        <html lang="en">
          <head></head>
          <body
            id="main-layout"
            className="flex flex-col min-h-screen m-0 bg-white text-black dark:bg-black dark:text-white"
          >
            {children}
            <Footer />
          </body>
        </html>
      </ReduxProvider>
    </NextAuthProvider>
  );
}
